---
- name: Setup firewall for Geth service
  hosts: ethereum
  become: true
  tasks:
  - name: Allow p2p port
    ufw:
      rule: allow
      port: "30303"

- name: Start Geth service
  hosts: ethereum
  roles:
  - role: 0x0i.geth
    vars:
      perform_uninstall: false
      install_type: archive
      archive_url: "https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-{{ geth_version }}.tar.gz"
      install_dir: "{{ geth_bin_path }}/geth"
      geth_config:
        Eth:
          SyncMode: snap
        Node:
          DataDir: "{{ geth_data_path }}/{{ geth_network }}"
      extra_run_args:
        - --{{ geth_network }}
        - --state.scheme=path
        - --maxpeers={{ geth_peers }}
        - --authrpc.jwtsecret={{secrets_path}}/jwtsecret
        - --authrpc.vhosts="*"
        - --http
        - --metrics
        - --pprof
