---
- name: Start & configure monitoring services
  hosts: ethereum
  become: true
  roles:
  - role: cloudalchemy.node_exporter

  - role: cloudalchemy.alertmanager
    vars:
      alertmanager_version: latest
      alertmanager_receivers:
        - name: empty
        - name: pagerduty-general
          pagerduty_configs:
            - service_key: "{{ alertmanager_pagerduty_general_key }}"
        - name: pagerduty-critical
          pagerduty_configs:
            - service_key: "{{ alertmanager_pagerduty_critical_key }}"
      alertmanager_route:
        group_by: ['service']
        receiver: pagerduty-general
        routes:
        - matchers: [ 'alertname="Watchdog"' ]
          receiver: empty
        - matchers: [ 'severity="critical"' ]
          receiver: pagerduty-critical
    when: alertmanager_enabled == true

  - role: cloudalchemy.prometheus
    vars:
      prometheus_version: latest
      prometheus_global:
        scrape_interval: 15s
        evaluation_interval: 15s
      prometheus_alertmanager_config:
      - static_configs:
        - targets: [ 'localhost:9093' ]
      prometheus_scrape_configs:
      - job_name: lhbn
        metrics_path: /metrics    
        static_configs:
          - targets: [ 'localhost:5054' ]
      - job_name: lhvc
        metrics_path: /metrics    
        static_configs:
          - targets: [ 'localhost:5064' ]
      - job_name: geth
        metrics_path: /debug/metrics/prometheus
        static_configs:
        - targets: [ 'localhost:6060' ]
      - job_name: node
        metrics_path: /metrics
        static_configs:
        - targets: [ 'localhost:9100' ]

  - role: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: admin # You'll be asked to change
      grafana_auth:
        anonymous:
          enabled: false
      grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://localhost:9090
      grafana_dashboards:
      - dashboard_id: '14053' # Geth
        revision_id: '1'
        datasource: prometheus
      - dashboard_id: '1860' # Node Exporter
        revision_id: '25'
        datasource: prometheus

  tasks:
  - name: Fix job parameter in the Geth dashboard
    replace:
      dest: "/var/lib/grafana/dashboards/14053.json"
      regexp: "\\${VAR_JOB}"
      replace: "geth"

  - name: Allow traffic to Grafana
    ufw:
      rule: allow
      port: "3000"
      proto: tcp

  - name: Allow traffic to Prometheus
    ufw:
      rule: allow
      port: "9090"
      proto: tcp
