---
- name: Setup firewall for monitoring services
  hosts: ethereum
  become: true
  tasks:
  - name: Enable UFW
    ufw:
      state: enabled

  - name: Allow Prometheus TCP port
    ufw:
      rule: allow
      port: '9090'
      proto: tcp

  - name: Allow Grafana TCP port
    ufw:
      rule: allow
      port: '3000'
      proto: tcp

- name: Start monitoring services
  hosts: ethereum
  roles:
  - role: cloudalchemy.node_exporter

  - role: cloudalchemy.prometheus
    vars:
      prometheus_scrape_configs:
      - job_name: geth
        metrics_path: /debug/metrics/prometheus
        static_configs:
        - targets:
          - localhost:6060
      - job_name: system
        metrics_path: /metrics
        static_configs:
        - targets:
          - localhost:9100

  - role: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: admin
      grafana_auth:
        anonymous:
          org_name: 'Main Org.'
          org_role: Viewer
      grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://localhost:9090
      grafana_dashboards:
      - dashboard_id: '14053'
        revision_id: '1'
        datasource: prometheus
      - dashboard_id: '1860'
        revision_id: '25'
        datasource: prometheus
      - dashboard_id: '3662'
        revision_id: '2'
        datasource: prometheus
