---
roles:
- src: jnv.unattended-upgrades
- src: 0x0i.systemd
- src: 0x0i.geth
- src: cloudalchemy.prometheus
- src: cloudalchemy.alertmanager
- src: cloudalchemy.grafana
- src: cloudalchemy.node_exporter
- src: githubixx.ansible_role_wireguard
- src: rofrantz.duckdns